spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/events
    username: root
    password: 123

  liquibase:
    change-log: db/changelog/main-changelog.xml
  sql:
    init:
      mode: always